services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: notehubDB
      POSTGRES_PASSWORD: notehub_password
      POSTGRES_USER: notehub
    ports:
      - "5432:5432"
  app:
    build: 
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=notehubDB
      - POSTGRES_USER=notehub
      - POSTGRES_PASSWORD=notehub_password